name: Generate and Attest SBOM
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Display structure of downloaded files
        id: list_files
        run: ls -R

      - name: Generate SBOM
        id: generate_sbom
        uses: anchore/sbom-action@v0
        with:
          file: './${{ inputs.artifact-name }}'
          format: 'spdx-json'
          output-file: './${{ inputs.artifact-name }}-sbom.spdx.json'

      - name: Generate SBOM attestation
        id: attest_sbom
        uses: actions/attest-sbom@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          subject-path: './${{ inputs.artifact-name }}'
          sbom-path: './${{ inputs.artifact-name }}-sbom.spdx.json'
          show-summary: true
    